use maestro_wish8.5 instead of wish8.5

diff --git a/bin/xm b/bin/xm
--- a/bin/xm
+++ b/bin/xm
@@ -5,7 +5,12 @@
 arch=`uname -s`
 
 if [[ "$arch" = "Linux" ]]; then
-       TCLSH=/home/binops/afsi/ssm/domain2/tcl-tk_8.5.11_linux26-i686/bin/wish8.5
+      #TCLSH=/home/binops/afsi/ssm/domain2/tcl-tk_8.5.11_linux26-i686/bin/wish8.5
+      TCLSH=$(which maestro_wish8.5)
+      if [[ "${TCLSH}" == "" ]] ; then
+         echo "ERROR: executable \"maestro_wish8.5\" not found! Cannot start application..."
+         exit 1
+      fi
 else
        echo "maestro_center is only supported on Linux platforms"
        exit 1
